-- Additive migration. Apply on staging, verify manager access, then production.
BEGIN;
-- Prerequisites: existing blogs table and the site's manager authorization helper.
DO $$
BEGIN
 IF to_regclass('public.blogs') IS NULL THEN
  RAISE EXCEPTION 'Missing public.blogs: apply the blogs table setup first.';
 END IF;
 IF to_regprocedure('public.is_manager()') IS NULL THEN
  RAISE EXCEPTION 'Missing public.is_manager(): apply the existing manager authorization setup first.';
 END IF;
END $$;

-- Older deployments kept these tables only in SQLite. Create missing Supabase
-- tables without replacing existing tables or importing/publishing old content.
CREATE TABLE IF NOT EXISTS public.resources (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 level text NOT NULL,
 subject text NOT NULL,
 resource_type text NOT NULL DEFAULT 'note',
 sub_type text NOT NULL DEFAULT '',
 title text NOT NULL DEFAULT '',
 description text NOT NULL DEFAULT '',
 url text NOT NULL DEFAULT '',
 published boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.pseo_pages (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 slug text NOT NULL UNIQUE,
 playbook_type text NOT NULL,
 title text NOT NULL,
 meta_description text NOT NULL DEFAULT '',
 primary_keyword text NOT NULL,
 secondary_keywords jsonb NOT NULL DEFAULT '[]'::jsonb,
 search_intent text NOT NULL DEFAULT 'informational',
 h1 text NOT NULL,
 introduction text NOT NULL DEFAULT '',
 sections jsonb NOT NULL DEFAULT '[]'::jsonb,
 faq jsonb NOT NULL DEFAULT '[]'::jsonb,
 call_to_action text NOT NULL DEFAULT '',
 schema_type text NOT NULL DEFAULT 'Article',
 schema_data jsonb NOT NULL DEFAULT '{}'::jsonb,
 internal_links jsonb NOT NULL DEFAULT '[]'::jsonb,
 related_pages jsonb NOT NULL DEFAULT '[]'::jsonb,
 parent_topic text NOT NULL DEFAULT '',
 cluster_topic text NOT NULL DEFAULT '',
 word_count integer NOT NULL DEFAULT 0,
 published boolean NOT NULL DEFAULT false,
 phase integer NOT NULL DEFAULT 1 CHECK (phase BETWEEN 1 AND 4),
 generation_batch text NOT NULL DEFAULT '',
 review_status text NOT NULL DEFAULT 'pending',
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.pseo_clusters (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL UNIQUE,
 parent_cluster text,
 description text NOT NULL DEFAULT '',
 hub_page_slug text,
 page_count integer NOT NULL DEFAULT 0,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.pseo_datasets (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_type text NOT NULL,
 name text NOT NULL,
 metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
 active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.pseo_generation_log (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id text NOT NULL UNIQUE,
 pages_requested integer NOT NULL DEFAULT 0,
 pages_generated integer NOT NULL DEFAULT 0,
 pages_skipped integer NOT NULL DEFAULT 0,
 playbook_types jsonb NOT NULL DEFAULT '[]'::jsonb,
 status text NOT NULL DEFAULT 'pending',
 error_log jsonb NOT NULL DEFAULT '[]'::jsonb,
 started_at timestamptz,
 completed_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now()
);

-- IF NOT EXISTS preserves existing tables; validate publication types explicitly.
DO $$
DECLARE entry record; actual text;
BEGIN
 FOR entry IN SELECT * FROM (VALUES ('blogs','integer'),('resources','boolean'),('pseo_pages','boolean')) AS required(name,kind)
 LOOP
  SELECT data_type INTO actual FROM information_schema.columns
   WHERE table_schema='public' AND table_name=entry.name AND column_name='published';
  IF actual IS DISTINCT FROM entry.kind THEN
   RAISE EXCEPTION 'public.%.published must be %, found %; existing data was not converted.',entry.name,entry.kind,coalesce(actual,'missing');
  END IF;
 END LOOP;
END $$;
CREATE INDEX IF NOT EXISTS resources_public_filters_idx ON public.resources (published,level,subject,resource_type);
CREATE INDEX IF NOT EXISTS pseo_public_updated_idx ON public.pseo_pages (published,updated_at);

ALTER TABLE public.blogs
 ADD COLUMN IF NOT EXISTS summary text DEFAULT '',
 ADD COLUMN IF NOT EXISTS author text,
 ADD COLUMN IF NOT EXISTS reviewer text,
 ADD COLUMN IF NOT EXISTS source_references jsonb NOT NULL DEFAULT '[]'::jsonb,
 ADD COLUMN IF NOT EXISTS last_verified_at date,
 ADD COLUMN IF NOT EXISTS published_at timestamptz,
 ADD COLUMN IF NOT EXISTS modified_at timestamptz,
 ADD COLUMN IF NOT EXISTS image_alt text DEFAULT '';
-- Historical author/publication/review dates deliberately remain NULL.
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
-- Existing service role bypasses RLS; an unrestricted FOR ALL policy was exposing drafts.
DROP POLICY IF EXISTS blogs_select ON public.blogs;
DROP POLICY IF EXISTS blogs_all_service ON public.blogs;
CREATE POLICY blogs_select ON public.blogs FOR SELECT USING (published = 1 OR public.is_manager());
-- Restrictive guards protect against other permissive policies already installed.
DROP POLICY IF EXISTS blogs_publication_guard ON public.blogs;
CREATE POLICY blogs_publication_guard ON public.blogs AS RESTRICTIVE FOR SELECT
 TO anon, authenticated USING (published = 1 OR public.is_manager());
-- Publication guards also constrain any existing permissive SELECT policies.
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS resources_publication_guard ON public.resources;
CREATE POLICY resources_publication_guard ON public.resources AS RESTRICTIVE FOR SELECT
 TO anon, authenticated USING (published = true OR public.is_manager());
ALTER TABLE public.pseo_pages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pseo_publication_guard ON public.pseo_pages;
CREATE POLICY pseo_publication_guard ON public.pseo_pages AS RESTRICTIVE FOR SELECT
 TO anon, authenticated USING (published = true OR public.is_manager());

-- Restrictive policies need a permissive policy too. Newly created public tables
-- expose only published rows; managers can read drafts and manage content.
DO $$
DECLARE name text; sequence_name text;
BEGIN
 FOREACH name IN ARRAY ARRAY['resources','pseo_pages','pseo_clusters','pseo_datasets','pseo_generation_log'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',name);
  EXECUTE format('DROP POLICY IF EXISTS seo_manager_access ON public.%I',name);
  EXECUTE format('CREATE POLICY seo_manager_access ON public.%I FOR ALL TO authenticated USING (public.is_manager()) WITH CHECK (public.is_manager())',name);
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated, service_role',name);
  sequence_name := pg_get_serial_sequence(format('public.%I',name),'id');
  IF sequence_name IS NOT NULL THEN
   EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated, service_role',sequence_name);
  END IF;
 END LOOP;
 FOREACH name IN ARRAY ARRAY['resources','pseo_pages'] LOOP
  EXECUTE format('DROP POLICY IF EXISTS seo_published_read ON public.%I',name);
  EXECUTE format('CREATE POLICY seo_published_read ON public.%I FOR SELECT TO anon, authenticated USING (published = true OR public.is_manager())',name);
  EXECUTE format('GRANT SELECT ON public.%I TO anon',name);
 END LOOP;
END $$;
NOTIFY pgrst, 'reload schema';
COMMIT;
