import {describe,it,expect} from 'vitest';
import {createPublicRepository} from '../../server/public/content.js';
import {mergedResources} from '../../src/public/load';
function stub(tableRows:Record<string,any[]>) {
 const calls:any[]=[];
 const client={from(table:string){let rows=[...(tableRows[table]||[])];let start=0,end=Infinity,one=false,head=false;const query:any={
 select(columns:string,options:any={}){calls.push(['select',table,columns,options]);head=options.head;return query;},
 eq(field:string,value:any){calls.push(['eq',table,field,value]);rows=rows.filter(r=>r[field]===value);return query;},
 neq(field:string,value:any){rows=rows.filter(r=>r[field]!==value);return query;},
 or(expression:string){calls.push(['or',expression]);return query;},
 order(){return query;},range(a:number,b:number){calls.push(['range',a,b]);start=a;end=b;return query;},limit(n:number){end=n-1;return query;},maybeSingle(){one=true;return query;},abortSignal(){return query;},
 then(resolve:any){const result=head?null:rows.slice(start,end+1);return Promise.resolve({data:one?result?.[0]||null:result,count:rows.length,error:null}).then(resolve);},
 };return query;}};
 return {client,calls};
}
describe('publication enforcement and database query behavior',()=>{
 it('never returns a draft through a detail lookup or list',async()=>{const {client,calls}=stub({blogs:[{id:1,slug:'draft',published:0,content:'private',secret:'never leak'},{id:2,slug:'public',published:1,content:'<script>X</script><p>Safe.</p>',source_references:[],secret:'never leak'}]});const r=createPublicRepository(client);expect(await r.blog('draft')).toBeNull();const blogs=await r.blogs();expect(blogs).toHaveLength(1);expect(blogs[0].content).toBe('<p>Safe.</p>');expect(blogs[0]).not.toHaveProperty('secret');expect(calls).toContainEqual(['eq','blogs','published',1]);});
 it('applies level, subject and type together and excludes unpublished resources',async()=>{const {client}=stub({resources:[{id:1,published:true,level:'Foundation',subject:'CT',resource_type:'note',url:'https://example.org/1'},{id:2,published:false,level:'Foundation',subject:'CT',resource_type:'video',url:'https://example.org/2'},{id:3,published:true,level:'Qualifier',subject:'CT',resource_type:'video',url:'https://example.org/3'},{id:4,published:true,level:'Foundation',subject:'Python',resource_type:'video',url:'https://example.org/4'},{id:5,published:true,level:'Foundation',subject:'CT',resource_type:'video',url:'https://example.org/5'}]});const r=createPublicRepository(client);const rows=await r.resources({level:'Foundation',subject:'CT',type:'video'});expect(rows.map(x=>x.id)).toEqual([5]);});
 it('uses exact filtered counts with page ranges',async()=>{const rows=Array.from({length:31},(_,i)=>({id:i,slug:'page-'+i,published:true,playbook_type:'guide',cluster_topic:'iitm'}));rows.push({id:99,slug:'draft',published:false,playbook_type:'guide',cluster_topic:'iitm'});const {client,calls}=stub({pseo_pages:rows});const result=await createPublicRepository(client).knowledgeList({page:2,limit:10,type:'guide',cluster:'iitm'});expect(result.pages).toHaveLength(10);expect(result.pages[0].slug).toBe('page-10');expect(result.pagination).toEqual({page:2,limit:10,total:31,totalPages:4});expect(calls).toContainEqual(['range',10,19]);});
 it('filters related pages by cluster or type and removes current and draft pages',async()=>{const {client}=stub({pseo_pages:[{slug:'current',published:true,cluster_topic:'ct',playbook_type:'guide'}, {slug:'cluster-match',published:true,cluster_topic:'ct',playbook_type:'lesson'}, {slug:'type-match',published:true,cluster_topic:'python',playbook_type:'guide'}, {slug:'unrelated',published:true,cluster_topic:'python',playbook_type:'lesson'}, {slug:'draft',published:false,cluster_topic:'ct',playbook_type:'guide'}]});const related=await createPublicRepository(client).related('current');expect(related.map(x=>x.slug).sort()).toEqual(['cluster-match','type-match']);expect(await createPublicRepository(client).knowledge('draft')).toBeNull();});
 it('retains resources reused across Qualifier and Foundation',()=>{const merged=mergedResources([]);const qualifier=merged.find(r=>r.level==='Qualifier'&&r.subject==='CT');expect(qualifier).toBeTruthy();expect(merged.some(r=>r.level==='Foundation'&&r.subject==='CT'&&r.url===qualifier!.url)).toBe(true);});
 it('deduplicates static and database notes by resource URL',()=>{const records=[{id:'one',level:'Foundation',subject:'CT',resource_type:'note' as const,sub_type:'Notes',title:'One',description:'Test',url:'https://example.org/duplicate'}, {id:'two',level:'Foundation',subject:'CT',resource_type:'note' as const,sub_type:'Notes',title:'Two',description:'Test',url:'https://example.org/duplicate'}];const merged=mergedResources(records,'Foundation','CT');expect(merged.filter(r=>r.url==='https://example.org/duplicate')).toHaveLength(1);expect(merged.some(r=>r.id.startsWith('fn-ct'))).toBe(true);});
});
