import {it,expect} from 'vitest';
import express from 'express';
import path from 'node:path';
import {createPublicHttp} from '../../server/public/http.js';
import * as renderer from '../../src/public/entry-server';
import {fixtureRepository,guides} from './fixtures.js';
async function running(http:any,check:(base:string)=>Promise<void>){const app=express();app.use(http.early);app.use(http.document);const s=app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>s.once('listening',resolve));try{await check(`http://127.0.0.1:${(s.address() as any).port}`);}finally{await new Promise<void>(resolve=>s.close(()=>resolve()));}}
it('keeps staging documents and crawler inventories out of indexing',async()=>{const http=await createPublicHttp({root:path.resolve('.'),renderer,repository:fixtureRepository(),staging:true});await running(http,async base=>{const r=await fetch(base+'/iitm-bs');expect(r.headers.get('x-robots-tag')).toContain('noindex');expect(await r.text()).toContain('content="noindex,follow"');expect(await(await fetch(base+'/robots.txt')).text()).toContain('Disallow: /');expect(await(await fetch(base+'/sitemap.xml')).text()).not.toContain('<sitemap>');expect(await(await fetch(base+'/llms.txt')).text()).not.toContain('/blog/');});});
it('gives archives real pagination links and consistent canonical/schema URLs',async()=>{const many=Array.from({length:20},(_,i)=>({...guides[0],id:i+1,slug:'published-'+i,title:'Published guide '+i}));const http=await createPublicHttp({root:path.resolve('.'),renderer,repository:fixtureRepository({blogs:async()=>many})});await running(http,async base=>{const html=await(await fetch(base+'/blog?page=2&utm_source=test')).text();expect(html).toContain('href="https://genziitian.in/blog?page=2"');expect(html).toContain('href="/blog?page=3"');expect(html).toContain('"url":"https://genziitian.in/blog?page=2"');expect(html).not.toContain('canonical" href="https://genziitian.in/blog?page=2&amp;utm');});});
it('does not include drafts or invalid knowledge destinations in crawl inventories',async()=>{const http=await createPublicHttp({root:path.resolve('.'),renderer,repository:fixtureRepository({allKnowledge:async()=>[{slug:'guide/valid',title:'Valid'},{slug:'blog/conflicting',title:'Collision'},{slug:'../bad',title:'Invalid'},{slug:'checkout/private',title:'Private'}]})});const inventory=await http.inventory();expect(inventory.knowledge.map((p:any)=>p.path)).toEqual(['/guide/valid']);});
